baseurl = "/"
languageCode = "en-us"
title = "ANTON"
pluralizelisttitles = false

[params]
relativeURLs = true
contentdir = "content"

[minify]
  minifyOutput = true
  
  
[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

