baseurl = "/"
languageCode = "en-us"
title = "collison"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-XXXXXXXX-Y"
sectionPagesMenu = "main"
pluralizelisttitles = false

[params]
relativeURLs = true
contentdir = "content"

  
[markup]
  defaultMarkdownHandler = "goldmark"

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

